/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.78
 * Generated at: 2023-08-17 08:43:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.ReportDAO;
import model.ComReportDTO;
import model.ComcDAO;
import model.ComcDTO;
import java.util.ArrayList;
import model.ComLikeDTO;
import model.LikesDAO;
import model.UsersDTO;
import java.io.PrintWriter;
import model.BoardDTO;
import model.BoardDAO;

public final class view_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

 public Boolean isLike(String userId, int comNum){
      LikesDAO ldao = new LikesDAO();
      return ldao.isComUserLiked(userId, comNum);
  }

 public Boolean isReport(String userId, int comNum){
      ReportDAO rdao = new ReportDAO();
      return rdao.isComUserReported(userId, comNum);
  }

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.io.PrintWriter");
    _jspx_imports_classes.add("model.BoardDAO");
    _jspx_imports_classes.add("model.ReportDAO");
    _jspx_imports_classes.add("model.LikesDAO");
    _jspx_imports_classes.add("model.ComReportDTO");
    _jspx_imports_classes.add("model.ComcDAO");
    _jspx_imports_classes.add("model.ComcDTO");
    _jspx_imports_classes.add("model.ComLikeDTO");
    _jspx_imports_classes.add("model.UsersDTO");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("model.BoardDTO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href= \"css/bootstrap.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<title>JSP 게시판 웹 사이트</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta name=\"description\"\r\n");
      out.write("   content=\"Free HTML5 Website Template by FreeHTML5.co\" />\r\n");
      out.write("<meta name=\"keywords\"\r\n");
      out.write("   content=\"free website templates, free html5, free template, free bootstrap, free website template, html5, css3, mobile first, responsive\" />\r\n");
      out.write("<meta name=\"author\" content=\"FreeHTML5.co\" />\r\n");
      out.write("\r\n");
      out.write("<!-- Facebook and Twitter integration -->\r\n");
      out.write("<meta property=\"og:title\" content=\"\" />\r\n");
      out.write("<meta property=\"og:image\" content=\"\" />\r\n");
      out.write("<meta property=\"og:url\" content=\"\" />\r\n");
      out.write("<meta property=\"og:site_name\" content=\"\" />\r\n");
      out.write("<meta property=\"og:description\" content=\"\" />\r\n");
      out.write("<meta name=\"twitter:title\" content=\"\" />\r\n");
      out.write("<meta name=\"twitter:image\" content=\"\" />\r\n");
      out.write("<meta name=\"twitter:url\" content=\"\" />\r\n");
      out.write("<meta name=\"twitter:card\" content=\"\" />\r\n");
      out.write("\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Lato:300,400,700\"\r\n");
      out.write("   rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Animate.css -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/animate.css\">\r\n");
      out.write("<!-- Icomoon Icon Fonts-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/icomoon.css\">\r\n");
      out.write("<!-- Themify Icons-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/themify-icons.css\">\r\n");
      out.write("<!-- Bootstrap  -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Magnific Popup -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/magnific-popup.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Magnific Popup -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap-datepicker.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Owl Carousel  -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/owl.carousel.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/owl.theme.default.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Theme style  -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/stylewrite.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Modernizr JS -->\r\n");
      out.write("<script src=\"js/modernizr-2.6.2.min.js\"></script>\r\n");
      out.write("<!-- FOR IE9 below -->\r\n");
      out.write("<!--[if lt IE 9]>\r\n");
      out.write("   <script src=\"js/respond.min.js\"></script>\r\n");
      out.write("   <![endif]-->\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    .post-actions {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        justify-content: space-between; /* 좌우 여백을 동일하게 분배 */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .action-buttons {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        gap: 10px; /* 버튼 간의 여백 설정 */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .like-button {\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        display: inline-block;\r\n");
      out.write("        border: none;\r\n");
      out.write("        background-color : aliceblue;\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("   .report-button {\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        display: inline-block;\r\n");
      out.write("        background-color : white;\r\n");
      out.write("        border: none;\r\n");
      out.write("    }\r\n");
      out.write("    .like-image  {\r\n");
      out.write("        width: 100px;\r\n");
      out.write("        height: 100px;\r\n");
      out.write("    }\r\n");
      out.write("    .report-image {\r\n");
      out.write("        width: 100px;\r\n");
      out.write("        height: 100px;\r\n");
      out.write("    }\r\n");
      out.write("    #com_content{\r\n");
      out.write("       resize : none;\r\n");
      out.write("       \r\n");
      out.write("    }\r\n");
      out.write("    .border-none{\r\n");
      out.write("       border : none;\r\n");
      out.write("       background-color: white;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .dadglespan{\r\n");
      out.write("       font-size: 20pt;\r\n");
      out.write("    }\r\n");
      out.write("    .datespan{\r\n");
      out.write("       font-size: 5pt;\r\n");
      out.write("    }\r\n");
      out.write("    .dadgleContent{\r\n");
      out.write("       font-size :15pt;\r\n");
      out.write("    }\r\n");
      out.write("    #dadgulWrite{\r\n");
      out.write("       font-size: 15px;\r\n");
      out.write("    }\r\n");
      out.write("    .deWrite{\r\n");
      out.write("   \r\n");
      out.write("       color: inherit;\r\n");
      out.write("    }\r\n");
      out.write("    .deWrite:hover{\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   \r\n");
      out.write("   <div class=\"gtco-loader\"></div>\r\n");
      out.write("   <div id=\"page\">\r\n");
      out.write("      <!-- <div class=\"page-inner\"> -->\r\n");
      out.write("      <nav class=\"gtco-nav\" role=\"navigation\">\r\n");
      out.write("         <div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("               <div class=\"col-sm-4 col-xs-12\">\r\n");
      out.write("                  <div id=\"gtco-logo\">\r\n");
      out.write("                     <a href=\"index.jsp\">AMORA</a>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"col-xs-8 text-right menu-1\">\r\n");
      out.write("                  <ul>\r\n");
      out.write("                     <li class =\"has-dropdown\"><a href=\"community.jsp\">커뮤니티</a>\r\n");
      out.write("                        <ul class=\"dropdown\">\r\n");
      out.write("                            <li><a href=\"community.jsp\">전체 글 보기</a></li>\r\n");
      out.write("                           <li><a href=\"request.jsp\">건의사항</a></li>\r\n");
      out.write("                           <li><a href=\"hobby.jsp\">취미생활</a></li>\r\n");
      out.write("                           <li><a href=\"baby.jsp\">육아</a></li>\r\n");
      out.write("                           <li><a href=\"find.jsp\">찾아주세요</a></li>\r\n");
      out.write("                           <li><a href=\"food.jsp\">동네맛집</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                     </li>\r\n");
      out.write("                     <li class =\"has-dropdown\"> <a href=\"secondhand.jsp\">중고거래/나눔</a>   \r\n");
      out.write("                        <ul class=\"dropdown\">\r\n");
      out.write("                           <li><a href=\"secondhand.jsp\">중고거래</a></li>\r\n");
      out.write("                           <li><a href=\"share.jsp\">나눔</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                     </li>\r\n");
      out.write("                     <li><a href=\"contact.jsp\">공동구매</a></li>\r\n");
      out.write("                     <li><a href=\"promotion.jsp\">홍보</a></li>\r\n");
      out.write("                     <li><a href=\"pricing.jsp\">공지사항</a></li>\r\n");
      out.write("                     <li><a href=\"destination.jsp\">마이페이지</a></li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("         </div>\r\n");
      out.write("      </nav>\r\n");
      out.write("\r\n");
      out.write("     <header id=\"gtco-header\" class=\"gtco-cover gtco-cover-sm\"\r\n");
      out.write("         role=\"banner\" style=\"background-image: url(images/bgapt.jpg); height: 150px\">\r\n");
      out.write("         <div class=\"overlay\"></div>\r\n");
      out.write("         <div class=\"gtco-container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("               <div class=\"col-md-12 col-md-offset-0 text-center\">\r\n");
      out.write("                  <div class=\"row row-mt-15em\">\r\n");
      out.write("                     <div class=\"col-md-12 mt-text animate-box\"\r\n");
      out.write("                        data-animate-effect=\"fadeInUp\">\r\n");
      out.write("                        <!-- <h1>Plans for Everyone</h1> -->\r\n");
      out.write("                     </div>\r\n");
      out.write("\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("      </header>	\r\n");
      out.write("\r\n");
      out.write("   <!-- <div class=\"gtco-section border-bottom\" >\r\n");
      out.write("      <div class=\"gtco-container\">\r\n");
      out.write("         <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-8 col-md-offset-2 text-center gtco-heading\">\r\n");
      out.write("               <h2>Choose The Best Plan For You</h2>\r\n");
      out.write("               <p>Join over 1 Million of users. Dignissimos asperiores vitae velit veniam totam fuga molestias accusamus alias autem provident. Odit ab aliquam dolor eius.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-4\">\r\n");
      out.write("               <div class=\"price-box\">\r\n");
      out.write("                  <h2 class=\"pricing-plan\">Starter</h2>\r\n");
      out.write("                  <div class=\"price\"><sup class=\"currency\">$</sup>7<small>/mo</small></div>\r\n");
      out.write("                  <p>Basic customer support for small business</p>\r\n");
      out.write("                  <hr>\r\n");
      out.write("                  <ul class=\"pricing-info\">\r\n");
      out.write("                     <li>10 projects</li>\r\n");
      out.write("                     <li>20 Pages</li>\r\n");
      out.write("                     <li>20 Emails</li>\r\n");
      out.write("                     <li>100 Images</li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                  <a href=\"#\" class=\"btn btn-default btn-sm\">Get started</a>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-4\">\r\n");
      out.write("               <div class=\"price-box\">\r\n");
      out.write("                  <h2 class=\"pricing-plan\">Regular</h2>\r\n");
      out.write("                  <div class=\"price\"><sup class=\"currency\">$</sup>19<small>/mo</small></div>\r\n");
      out.write("                  <p>Basic customer support for small business</p>\r\n");
      out.write("                  <hr>\r\n");
      out.write("                  <ul class=\"pricing-info\">\r\n");
      out.write("                     <li>15 projects</li>\r\n");
      out.write("                     <li>40 Pages</li>\r\n");
      out.write("                     <li>40 Emails</li>\r\n");
      out.write("                     <li>200 Images</li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                  <a href=\"#\" class=\"btn btn-default btn-sm\">Get started</a>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-4\">\r\n");
      out.write("               <div class=\"price-box popular\">\r\n");
      out.write("                  <div class=\"popular-text\">Popular</div>\r\n");
      out.write("                  <h2 class=\"pricing-plan\">Plus</h2>\r\n");
      out.write("                  <div class=\"price\"><sup class=\"currency\">$</sup>79<small>/mo</small></div>\r\n");
      out.write("                  <p>Basic customer support for small business</p>\r\n");
      out.write("                  <hr>\r\n");
      out.write("                  <ul class=\"pricing-info\">\r\n");
      out.write("                     <li>Unlimitted projects</li>\r\n");
      out.write("                     <li>100 Pages</li>\r\n");
      out.write("                     <li>100 Emails</li>\r\n");
      out.write("                     <li>700 Images</li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                  <a href=\"#\" class=\"btn btn-primary btn-sm\">Get started</a>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div> -->\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("   ");
 
      
      UsersDTO info =(UsersDTO)session.getAttribute("info"); 
         if (info ==null){
            response.sendRedirect("index.jsp");
         }
      String nickname = info.getNickname();
      BoardDAO bdao = new BoardDAO();
      LikesDAO ldao = new LikesDAO();
      int com_Num = 0;
      
      if (request.getParameter("com_Num") != null) {
         com_Num = Integer.parseInt(request.getParameter("com_Num")); // COMNUM 게시글 번호 
         //SQL ROWNUM ORDER BY COM_DATE DESC;
         
         //SELECT COM_CATEGORY, COM_NUM, COM_TITLE, NICKNAME, COM_DATE, COM_VIEWS FROM COMMUNITY ORDER BY COM_NUM DESC;
         
      }
       if (com_Num == 0) {
         PrintWriter script = response.getWriter();
         script.println("<script>");
         script.println("alert('유효하지 않는 글입니다.')");
         script.println("location.href = 'community.jsp'");
         script.println("history.back()");
         script.println("</script>");
       }
      
      BoardDTO dto = new BoardDAO().getBoardDTO(com_Num);
      
   
      out.write("\r\n");
      out.write(" <!--  <nav class=\"navbar navbar-default\">\r\n");
      out.write("      <div class=\"navbar-header\">\r\n");
      out.write("         <button type=\"button\" class=\"navbar-toggle collapsed\"\r\n");
      out.write("            data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\"\r\n");
      out.write("            aria-expanded=\"false\">\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("         </button>\r\n");
      out.write("         <a class=\"navbar-brand\" href=\"community.jsp\">AMORA</a>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("         <ul class=\"nav navbar-nav\">\r\n");
      out.write("            <li><a href=\"index.jsp\">메인</a></li>\r\n");
      out.write("            <li class=\"active\"><a href=\"community.jsp\">게시판</a></li>\r\n");
      out.write("         </ul>\r\n");
      out.write("         ");
 
            if (nickname == null) {
         
      out.write("\r\n");
      out.write("         <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("            <li class=\"dropdown\">\r\n");
      out.write("               <a href=\"#\" class=\"dropdown-toggle\"\r\n");
      out.write("                  data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\"\r\n");
      out.write("                  aria-expanded=\"false\">접속하기<span class=\"caret\"></span></a>\r\n");
      out.write("               <ul class=\"dropdown-menu\">\r\n");
      out.write("                  <li><a href=\"index.jsp\">로그인</a></li>\r\n");
      out.write("                  <li><a href=\"join.jsp\">회원가입</a></li>\r\n");
      out.write("               </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("         </ul>\r\n");
      out.write("         ");
       
            } else {
         
      out.write("\r\n");
      out.write("         <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("            <li class=\"dropdown\">\r\n");
      out.write("               <a href=\"#\" class=\"dropdown-toggle\"\r\n");
      out.write("                  data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\"\r\n");
      out.write("                  aria-expanded=\"false\">마이페이지<span class=\"caret\"></span></a>\r\n");
      out.write("               <ul class=\"dropdown-menu\">\r\n");
      out.write("                  <li><a href=\"logoutAction.jsp\">로그아웃</a></li>\r\n");
      out.write("               </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("         </ul>\r\n");
      out.write("         ");
      
            }
         
      out.write("\r\n");
      out.write("         \r\n");
      out.write("      </div>\r\n");
      out.write("   </nav> -->\r\n");
      out.write("\r\n");
      out.write("   <div class=\"container\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("         <table class=\"table table-striped\" style=\"text-align: center; border: 1px solid #dddddd\">\r\n");
      out.write("            <thead>\r\n");
      out.write("               <tr>\r\n");
      out.write("                  <th colspan=\"3\" style=\"background-color: #eeeeee; text-align: center;\">게시판 글보기</th>                  \r\n");
      out.write("               </tr>\r\n");
      out.write("            </thead>\r\n");
      out.write("            <tbody>\r\n");
      out.write("               <tr>\r\n");
      out.write("                  <td style=\"width: 20%;\">글제목</td>\r\n");
      out.write("                  <td colspan=\"2\">");
      out.print( dto.getCom_Title().replaceAll(" ", "&nbsp;").replaceAll("<", "&lt;").replaceAll(">","&gt;").replaceAll("\n", "<br>") );
      out.write("</td>\r\n");
      out.write("               </tr>\r\n");
      out.write("               <tr>\r\n");
      out.write("                  <td>카테고리</td>\r\n");
      out.write("                  <td colspan=\"2\">");
      out.print( dto.getCom_Category());
      out.write("</td>   \r\n");
      out.write("               </tr>\r\n");
      out.write("               <tr>\r\n");
      out.write("                  <td>작성자</td>\r\n");
      out.write("                  <td colspan=\"2\">");
      out.print( dto.getNickname() );
      out.write("</td>\r\n");
      out.write("               </tr>\r\n");
      out.write("               <tr>\r\n");
      out.write("                  <td>작성일자</td>\r\n");
      out.write("                  <td colspan=\"2\">");
      out.print( dto.getCom_Date().substring(0, 11) + dto.getCom_Date().substring(11, 13) + "시" + dto.getCom_Date().substring(14, 16) + "분 " );
      out.write("</td>\r\n");
      out.write("               </tr>\r\n");
      out.write("               <tr>\r\n");
      out.write("                  <td>내용</td>\r\n");
      out.write("                  <td colspan=\"2\" style=\"min-height: 200px; text-align: left;\">");
      out.print( dto.getCom_Content().replaceAll(" ", "&nbsp;").replaceAll("<", "&lt;").replaceAll(">","&gt;").replaceAll("\n", "<br>") );
      out.write("</td>\r\n");
      out.write("             \r\n");
      out.write("                         ");
      out.write("\r\n");
      out.write("               ");
      out.write("\r\n");
      out.write("            ");

               BoardDAO dao = new BoardDAO();
               String imagePath = dao.com_img(com_Num);
                                     
               if(imagePath == null){
                 imagePath = "/sh_img/빈사진.jpg";
               }
            
      out.write("\r\n");
      out.write("            \r\n");
      out.write("            ");
      out.write("\r\n");
      out.write("            <tr>\r\n");
      out.write("                  <td colspan=\"2\">사 진</td>\r\n");
      out.write("           </tr>\r\n");
      out.write("           <tr>\r\n");
      out.write("                  <td colspan=\"2\" style=\"max-height:100px;\"><img style=\"object-fit:cover; width: 100%; height:100%;\"class=\"card-img-top\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.print(imagePath);
      out.write("\"  alt=\"...\" /></td>        \r\n");
      out.write("           </tr>\r\n");
      out.write("            </tbody>\r\n");
      out.write("         </table>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("                \r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("         <!--  여기서부터는 좋아요,신고 기능입니다 -->\r\n");
      out.write("            ");
      out.write("\r\n");
      out.write("<!-- 신고기능 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("         ");

         // 좋아요와 신고기능.
         ComLikeDTO cldto =new ComLikeDTO(info.getId(),com_Num );
         int comLikenum =ldao.getComLike_num(cldto);
         ComReportDTO crdto = new ComReportDTO(info.getId(),com_Num); 
        
         String likeServlet = "";
         String likeUrl ="";
         String reportServelt ="";
         String reportUrl ="";
         if (isLike(info.getId(), com_Num)){
            likeServlet = "BoardunLikeUpdateAction";
            likeUrl = "./images/liked.png";
         }   
            else{
            likeServlet = "BoardLikeUpdateAction";
            likeUrl = "./images/unLiked.png";
         }
         if (isReport(info.getId(), com_Num)){
            reportServelt = "BoardUnReportUpdateAction";
            reportUrl = "./images/reported.png";
         }   
            else{
           reportServelt = "BoardReportUpdateAction";
            reportUrl = "./images/unReported.png";
         }
         
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("<input type=\"hidden\" id=\"isLiked\" value='");
      out.print( isLike(info.getId(), com_Num) ? "true" : "false" );
      out.write("'>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<form id=\"like_form\" action=\"");
      out.print( likeServlet );
      out.write("\" method=\"post\">\r\n");
      out.write("   <input type=\"hidden\" name=\"command\" value=\"like_it\">\r\n");
      out.write("   <input type=\"hidden\" name=\"com_Num\" value=");
      out.print(com_Num);
      out.write(">\r\n");
      out.write("   <div><button type=\"button\" onclick=\"toggleLike()\" class =\"like-button\" ><img id=\"likeImage\" src=\"");
      out.print( likeUrl );
      out.write("\" alt=\"좋아요!\" class =\"like-image\"></button></div>\r\n");
      out.write("   <div id=\"like_result\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.like_it}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("</form>\r\n");
int likes= bdao.getCom_Likes(com_Num); 
      out.write("\r\n");
      out.write("<span>좋아요");
      out.print(likes);
      out.write("</span>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 신고 버튼 -->\r\n");
      out.write("<form id=\"report_form\" action=\"");
      out.print( reportServelt );
      out.write("\" method=\"post\">\r\n");
      out.write("   <input type=\"hidden\" name=\"command\" value=\"like_it\">\r\n");
      out.write("   <input type=\"hidden\" name=\"com_Num\" value=");
      out.print(com_Num);
      out.write(">\r\n");
      out.write("   <div><button type=\"button\" onclick=\"toggleReport()\" class =\"report-button\" ><img id=\"reportImage\" src=\"");
      out.print( reportUrl );
      out.write("\" alt=\"신고\" class =\"report-image\" ></button></div>\r\n");
      out.write("   <div id=\"report_result\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.report_it}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
int reports= bdao.getCom_Report(com_Num); 
      out.write("\r\n");
      out.write("<!-- 신고 상태를 추적하기 위한 숨겨진 필드 추가 -->\r\n");
      out.write("<input type=\"hidden\" id=\"isReported\" value='");
      out.print( isReport(info.getId(), com_Num) ? "true" : "false" );
      out.write("'>\r\n");
      out.write("<div class=\"post-actions\">\r\n");
      out.write("          <div class=\"action-buttons\">\r\n");
      out.write("\r\n");
      out.write("         ");

         if (nickname != null && nickname.equals(dto.getNickname())) {
             
      out.write("\r\n");
      out.write("                  <a href=\"community.jsp\" class=\"btn btn-primary\">목록</a>\r\n");
      out.write("                   <a href=\"update.jsp?com_Num=");
      out.print( com_Num );
      out.write("\" class=\"btn btn-primary\">수정</a>\r\n");
      out.write("                   <a onclick=\"return confirm('정말로 삭제하시겠습니까?')\" href=\"deleteAction?com_Num=");
      out.print( com_Num );
      out.write("&com_Category=");
      out.print( dto.getCom_Category() );
      out.write("\" class=\"btn btn-primary\">삭제</a>\r\n");
      out.write("                   <!-- 삭제의 기준이 되는 com_Num과 com_Category의 값을 무조건 받아야함,그래서 전달도 같이 해줘야함. -->\r\n");
      out.write("             ");

                }
             
      out.write("      \r\n");
      out.write("         </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");

    int comNum = Integer.parseInt(request.getParameter("com_Num"));// URL 또는 폼에서 "comNum" 파라미터를 가져와 정수로 변환 여기서는 url
    ComcDAO comcdao= new ComcDAO();
    ArrayList<ComcDTO> list = comcdao.vogiReply(comNum); //계층형으로 처리된 리스트


      out.write("\r\n");
      out.write("<!--  여기서부터는 댓글창입니다. -->\r\n");
      out.write("<div class = \"reply.wrap\">\r\n");
      out.write("   <div class =\"reply index\">\r\n");
      out.write("   <hr>\r\n");
      out.write("   <h3>댓글창</h3>\r\n");
      out.write("      <div style=\"margin: 0 5%; padding-left: 10px; \">\r\n");
      out.write("      <button onclick=\"showReplyForm()\" class= \"border-none\" id = \"dadgulWrite\">댓글 쓰기</button>\r\n");
      out.write("   <form action =\"WriteComReply\" method =\"post\"  id =\"replyForm\" style =\"display: none;\">\r\n");
      out.write("   <input type =\"hidden\" name =\"com_Num\" value =\"");
      out.print( com_Num );
      out.write("\">\r\n");
      out.write("   <textarea name=\"com_content\" cols=\"80\" rows =\"2\" id = \"com_content\" style=\"padding-left:10%; \"></textarea>\r\n");
      out.write("    <button type=\"submit\" class=\"border-none\" style=\"font-size: 60%;\">댓글 등록</button>\r\n");
      out.write("    \r\n");
      out.write("   </form>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("   <br>\r\n");
      out.write("   </div>\r\n");
      out.write("   <br>\r\n");
      out.write("   <div class = \"replies\"> <!-- 댓글 쓰기 창 아래에 이제 댓글 보는 칸 -->\r\n");
      out.write("    ");
 for (int i = 0 ; i< list.size(); i++) { 
      out.write("\r\n");
      out.write("    \r\n");
      out.write("   ");
 if(list.get(i).getDadat() == 0) { 
      out.write(" <!-- 예를 들어 dadat가 0 일때만 대댓글 작성을 허용 --> \r\n");
      out.write("    <div class = \"dadgle\">\r\n");
      out.write("    <span class = \"dadglespan\">");
      out.print( list.get(i).getNickname() );
      out.write("</span>\r\n");
      out.write("    <span class =\"datespan\" >");
      out.print( list.get(i).getComcDate());
      out.write("</span>\r\n");
      out.write("    <br>\r\n");
      out.write("    <span class = \"dadgleContent\">");
      out.print(list.get(i).getComcContent() );
      out.write("</span>\r\n");
      out.write("    <br>\r\n");
      out.write("          <div>\r\n");
      out.write("          <br>\r\n");
      out.write("          ");
if(!list.get(i).getComcContent().equals("삭제된 댓글 입니다.")){ 
      out.write("\r\n");
      out.write("            <button class = \"border-none\" onclick=\"showSubReplyForm(");
      out.print(i);
      out.write(")\" style=\"flex-right\">답글 쓰기</button>\r\n");
      out.write("                <form action=\"WriteComSubReply\" method=\"post\" class=\"SubReplyForm\" id=\"SubReplyForm_");
      out.print( i );
      out.write("\" style=\"display: none;\">\r\n");
      out.write("                    <input type=\"hidden\" name=\"com_Num\" value=\"");
      out.print(com_Num);
      out.write("\">\r\n");
      out.write("                    <input type = \"hidden\" name = \"pcomcnum\" value =\"");
      out.print(list.get(i).getComcNum());
      out.write("\" >\r\n");
      out.write("                    <textarea name=\"subcomcContent\" cols=\"150\" rows=\"4\"></textarea>\r\n");
      out.write("                    <button type=\"submit\" class=\"border-none\">답글 등록</button>\r\n");
      out.write("                    </form>\r\n");
      out.write("          \r\n");
      out.write("          ");
 } 
      out.write("\r\n");
      out.write("          ");
 if(list.get(i).getNickname().equals(info.getNickname())){ 
      out.write("\r\n");
      out.write("          <!--  댓글 수정 -->\r\n");
      out.write("          ");
if(!list.get(i).getComcContent().equals("삭제된 댓글 입니다.")){ 
      out.write("\r\n");
      out.write("            <button onclick=\"showReplyUpdateForm()\" style =\"flex-right\" class = \"border-none\">댓글수정</button>\r\n");
      out.write("            <form action =\"UpdateReply\" method =\"post\" class =\"ReplyUpdateForm\" id = \"ReplyUpdateForm\" style= \"display: none;\">\r\n");
      out.write("            <input type =\"hidden\" name =\"com_Num\" value =\"");
      out.print( com_Num );
      out.write("\">\r\n");
      out.write("            <input type = \"hidden\" name = \"com_Likes\" value =\"");
      out.print(likes);
      out.write("\">\r\n");
      out.write("                    <input type = \"hidden\" name = \"comc_Num\" value =\"");
      out.print(list.get(i).getComcNum());
      out.write("\" >\r\n");
      out.write("                    <textarea name=\"comcContent\" cols=\"150\" rows=\"4\"></textarea>\r\n");
      out.write("                    <button type=\"submit\" class=\"border-none\">댓글 수정</button>\r\n");
      out.write("                    </form>\r\n");
      out.write("            <!--  댓글 삭제 -->\r\n");
      out.write("           <a class= \"deWrite\" href=\"javascript:replyDelete()\">댓글 삭제</a>\r\n");
      out.write("            <form action =\"DeleteComcReply\" method =\"post\"  id=\"repplyFrm\">\r\n");
      out.write("            <input type =\"hidden\" name =\"com_Num\" value =\"");
      out.print( com_Num );
      out.write("\">\r\n");
      out.write("                    <input type = \"hidden\" name = \"comc_Num\" value =\"");
      out.print(list.get(i).getComcNum());
      out.write("\">\r\n");
      out.write("                    <input type = \"hidden\" name = \"com_Likes\" value =\"");
      out.print(likes);
      out.write("\">\r\n");
      out.write("                    <!-- <input type=\"submit\" class=\"border-none\" value =\"댓글 삭제\"> -->\r\n");
      out.write("             </form>\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            </div>\r\n");
      out.write("            ");
} 
      out.write("\r\n");
      out.write("             ");
 } 
      out.write("       \r\n");
      out.write("            \r\n");
      out.write("    </div>\r\n");
      out.write("        ");
}else{ 
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("    <div class = \"dadgle\">\r\n");
      out.write("        <span style =\"padding-right : 100px;\"></span>\r\n");
      out.write("    \r\n");
      out.write("    <span class = \"dadglespan\">");
      out.print( list.get(i).getNickname() );
      out.write("</span>\r\n");
      out.write("    \r\n");
      out.write("    <span class =\"datespan\" >");
      out.print( list.get(i).getComcDate());
      out.write("</span>\r\n");
      out.write("    <br>\r\n");
      out.write("        <span style =\"padding-right : 100px;\"></span>\r\n");
      out.write("    \r\n");
      out.write("    <span class = \"dadgleContent\">");
      out.print(list.get(i).getComcContent() );
      out.write("</span>\r\n");
      out.write("            ");
 if(list.get(i).getNickname().equals(info.getNickname())){ 
      out.write("\r\n");
      out.write("          <span style =\"padding-right : 100px;\"></span>\r\n");
      out.write("          <!--  댓글 수정 -->\r\n");
      out.write("          ");
if(!list.get(i).getComcContent().equals("삭제된 댓글 입니다.")){ 
      out.write("\r\n");
      out.write("          <br>\r\n");
      out.write("          <span style =\"padding-right : 100px;\"></span>\r\n");
      out.write("            <button class =\"border-none\" onclick=\"showReReplyUpdateForm(");
      out.print(i);
      out.write(")\" style = \"flex-right\">답글 수정</button>\r\n");
      out.write("            <form action =\"UpdateReply\" method =\"post\" class =\"ReplyUpdateForm\" id = \"ReReplyUpdateForm_");
      out.print( i );
      out.write("\" style= \"display: none;\">\r\n");
      out.write("                  <input type=\"hidden\" name=\"comc_Num\" value=\"");
      out.print(list.get(i).getComcNum());
      out.write("\">\r\n");
      out.write("                    <input type =\"hidden\" name =\"com_Num\" value =\"");
      out.print( com_Num );
      out.write("\">\r\n");
      out.write("                    <textarea name=\"comcContent\" cols=\"150\" rows=\"4\"></textarea>\r\n");
      out.write("                    <input type = \"hidden\" name = \"com_Likes\" value =\"");
      out.print(likes);
      out.write("\">\r\n");
      out.write("                    <button type=\"submit\" class=\"border-none\">댓글 수정</button>\r\n");
      out.write("                    </form>\r\n");
      out.write("           <!--  댓글 삭제 -->\r\n");
      out.write("           <a class= \"deWrite\" href=\"javascript:replyDelete1()\">답글 삭제</a>\r\n");
      out.write("            <form action =\"DeleteComcReply\" method =\"post\" id=\"repplyFrm1\">\r\n");
      out.write("            <input type =\"hidden\" name =\"com_Num\" value =\"");
      out.print( com_Num );
      out.write("\">\r\n");
      out.write("                    <input type = \"hidden\" name = \"comc_Num\" value =\"");
      out.print(list.get(i).getComcNum());
      out.write("\">\r\n");
      out.write("                    <input type = \"hidden\" name = \"com_Likes\" value =\"");
      out.print(likes);
      out.write("\">\r\n");
      out.write("                    <!-- <input type=\"submit\" class=\"border-none\" value =\"댓글 삭제\"> -->\r\n");
      out.write("                    </form>\r\n");
      out.write("            \r\n");
      out.write("            </div>\r\n");
      out.write("             ");
} 
      out.write("\r\n");
      out.write("             ");
 } 
      out.write("     \r\n");
      out.write("            \r\n");
      out.write("            ");
} 
      out.write("      <!-- 예를 들어 dadat가 0 일때만 대댓글 작성을 허용 -->\r\n");
      out.write("    <br>\r\n");
      out.write("    </div>\r\n");
      out.write("        \r\n");
      out.write("    <hr>\r\n");
      out.write("   ");
} 
      out.write("\r\n");
      out.write("   \r\n");
      out.write("    \r\n");
      out.write("    ");
if(list.size()>=6){
      out.write("\r\n");
      out.write("    <hr>\r\n");
      out.write("   <button onclick=\"showReplyForm6()\" class = \"border-none\">댓글 쓰기</button>\r\n");
      out.write("   <form action =\"WriteComReply\" method =\"post\"  id =\"replyForm6\" style =\"display: none;\">\r\n");
      out.write("   <input type =\"hidden\" name =\"com_Num\" value =\"");
      out.print( com_Num );
      out.write("\">\r\n");
      out.write("   <textarea name=\"comcContent\" cols=\"150\" rows =\"3\" id = \"com_content\"></textarea>\r\n");
      out.write("    <button type=\"submit\" class=\"reply-write\">댓글 등록</button>\r\n");
      out.write("   </form>\r\n");
      out.write("    ");
 }
      out.write("\r\n");
      out.write("   </div> \r\n");
      out.write("   \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function replyDelete(){\r\n");
      out.write("   alert(\"OK\");\r\n");
      out.write("   document.getElementById('repplyFrm').submit();   \r\n");
      out.write("}\r\n");
      out.write("function replyDelete1(){\r\n");
      out.write("   document.getElementById('repplyFrm1').submit();      \r\n");
      out.write("}\r\n");
      out.write("function toggleLike() {\r\n");
      out.write("    // 좋아요 상태를 가져옵니다.\r\n");
      out.write("    var isLiked = document.getElementById('isLiked').value === \"true\";\r\n");
      out.write("    \r\n");
      out.write("    // 폼과 이미지 엘리먼트를 가져옵니다.\r\n");
      out.write("    var likeForm = document.getElementById('like_form');\r\n");
      out.write("    var likeImage = document.getElementById('likeImage');\r\n");
      out.write("    \r\n");
      out.write("    // 좋아요 상태를 변경하고 이미지를 업데이트합니다.\r\n");
      out.write("    if (isLiked) {\r\n");
      out.write("        likeImage.src = \"./images/unliked.png\";\r\n");
      out.write("        likeForm.action = \"BoardUnLikeUpdateAction\";\r\n");
      out.write("        document.getElementById('isLiked').value = \"false\";\r\n");
      out.write("    } else {\r\n");
      out.write("        likeImage.src = \"./images/liked.png\";\r\n");
      out.write("        likeForm.action = \"BoardLikeUpdateAction\";\r\n");
      out.write("        document.getElementById('isLiked').value = \"true\";\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    // 폼을 제출합니다.\r\n");
      out.write("    likeForm.submit();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function toggleReport() {\r\n");
      out.write("    // 신고 상태를 가져옵니다.\r\n");
      out.write("    var isReported = document.getElementById('isReported').value === \"true\";\r\n");
      out.write("\r\n");
      out.write("    // 신고 상태에 따라 확인 메시지를 선택합니다.\r\n");
      out.write("    var confirmMessage = isReported ? \"이 글의 신고를 취소하시겠습니까?\" : \"이 글을 신고하시겠습니까?\";\r\n");
      out.write("    var userConfirm = confirm(confirmMessage);\r\n");
      out.write("    if (!userConfirm){\r\n");
      out.write("       return; // 사용자가 취소를 선택하면 함수를 종료\r\n");
      out.write("    }else{\r\n");
      out.write("       \r\n");
      out.write("\r\n");
      out.write("    // 폼과 이미지 엘리먼트를 가져옵니다.\r\n");
      out.write("    var reportForm = document.getElementById('report_form');\r\n");
      out.write("    var reportImage = document.getElementById('reportImage');\r\n");
      out.write("    \r\n");
      out.write("    // 신고 상태를 변경하고 이미지를 업데이트합니다.\r\n");
      out.write("    if (isReported) {\r\n");
      out.write("        reportImage.src = \"./images/unReported.png\";\r\n");
      out.write("        reportForm.action = \"BoardUnReportUpdateAction\";\r\n");
      out.write("        document.getElementById('isReported').value = \"false\";\r\n");
      out.write("    } else {\r\n");
      out.write("        reportImage.src = \"./images/Reported.png\";\r\n");
      out.write("        reportForm.action = \"BoardReportUpdateAction\";\r\n");
      out.write("        document.getElementById('isReported').value = \"true\";\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    // 폼을 제출합니다.\r\n");
      out.write("    reportForm.submit();\r\n");
      out.write("    }alert('반영되었습니다.')\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function showReplyForm() {\r\n");
      out.write("    // 폼의 표시 상태를 변경합니다.\r\n");
      out.write("    var form = document.getElementById('replyForm');\r\n");
      out.write("    if(form.style.display === 'none') {\r\n");
      out.write("        form.style.display = 'block';\r\n");
      out.write("    } else {\r\n");
      out.write("        form.style.display = 'none';\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function showReplyForm6() {\r\n");
      out.write("    // 폼의 표시 상태를 변경합니다.\r\n");
      out.write("    var form = document.getElementById('replyForm6');\r\n");
      out.write("    if(form.style.display === 'none') {\r\n");
      out.write("        form.style.display = 'block';\r\n");
      out.write("    } else {\r\n");
      out.write("        form.style.display = 'none';\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("function showSubReplyForm(index) {\r\n");
      out.write("    // 폼의 표시 상태를 변경합니다.\r\n");
      out.write("    var form = document.getElementById('SubReplyForm_' + index);\r\n");
      out.write("    if(form.style.display === 'none') {\r\n");
      out.write("        form.style.display = 'block';\r\n");
      out.write("    } else {\r\n");
      out.write("        form.style.display = 'none';\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("function showReplyUpdateForm() {\r\n");
      out.write("    // 폼의 표시 상태를 변경합니다.\r\n");
      out.write("    var form = document.getElementById('ReplyUpdateForm');\r\n");
      out.write("    if(form.style.display === 'none') {\r\n");
      out.write("        form.style.display = 'block';\r\n");
      out.write("    } else {\r\n");
      out.write("        form.style.display = 'none';\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function showReReplyUpdateForm(index) {\r\n");
      out.write("    // 폼의 표시 상태를 변경합니다.\r\n");
      out.write("    var form = document.getElementById('ReReplyUpdateForm_' + index);\r\n");
      out.write("    if(form.style.display === 'none') {\r\n");
      out.write("        form.style.display = 'block';\r\n");
      out.write("    } else {\r\n");
      out.write("        form.style.display = 'none';\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("   <footer style=\"padding-top:0px;position:relative; top: 100px; left: 100px;\" id=\"gtco-footer\" role=\"contentinfo\">\r\n");
      out.write("      <div class=\"gtco-container\">\r\n");
      out.write("         <div class=\"row row-p   b-md\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-md-4\">\r\n");
      out.write("               <div class=\"gtco-widget\">\r\n");
      out.write("                  <h3>About Us</h3>\r\n");
      out.write("                  <p>아모라 아파트</p>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div style =\"position:relative; right:2000px;\"class=\"col-md-2 col-md-push-1\">\r\n");
      out.write("               <div class=\"gtco-widget\">\r\n");
      out.write("                  <h3>관리사무소</h3>\r\n");
      out.write("                  <ul class=\"gtco-footer-links\">\r\n");
      out.write("                     <li><a href=\"#\">사과시 복숭아동 아모라아파트</a></li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div style=\"position: relative; right: 150px;\"class=\"col-md-3 col-md-push-1\">\r\n");
      out.write("               <div class=\"gtco-widget\">\r\n");
      out.write("                  <h3>Get In Touch</h3>\r\n");
      out.write("                  <ul class=\"gtco-quick-contact\">\r\n");
      out.write("                     <li><a href=\"#\"><i class=\"icon-phone\"></i> +1 234 567\r\n");
      out.write("                           890</a></li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("         </div>\r\n");
      out.write("\r\n");
      out.write("         <div class=\"row copyright\">\r\n");
      out.write("            <div class=\"col-md-12\">\r\n");
      out.write("               <p class=\"pull-left\">\r\n");
      out.write("                  <small class=\"block\">&copy; 2016 Free HTML5. All Rights\r\n");
      out.write("                     Reserved.</small> <small class=\"block\">Designed by <a\r\n");
      out.write("                     href=\"https://freehtml5.co/\" target=\"_blank\">freehtml5.co</a>\r\n");
      out.write("                     Demo Images: <a href=\"http://unsplash.com/\" target=\"_blank\">Unsplash</a></small>\r\n");
      out.write("               </p>\r\n");
      out.write("               <p class=\"pull-right\">\r\n");
      out.write("               <ul class=\"gtco-social-icons pull-right\">\r\n");
      out.write("                  <li><a href=\"#\"><i class=\"icon-twitter\"></i></a></li>\r\n");
      out.write("                  <li><a href=\"#\"><i class=\"icon-facebook\"></i></a></li>\r\n");
      out.write("                  <li><a href=\"#\"><i class=\"icon-linkedin\"></i></a></li>\r\n");
      out.write("                  <li><a href=\"#\"><i class=\"icon-dribbble\"></i></a></li>\r\n");
      out.write("               </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("   </footer>\r\n");
      out.write("   <!-- </div> -->\r\n");
      out.write("\r\n");
      out.write("   <div class=\"gototop js-top\">\r\n");
      out.write("      <a href=\"#\" class=\"js-gotop\"><i class=\"icon-arrow-up\"></i></a>\r\n");
      out.write("   </div>\r\n");
      out.write("\r\n");
      out.write("   <!-- jQuery -->\r\n");
      out.write("   <script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("   <!-- jQuery Easing -->\r\n");
      out.write("   <script src=\"js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("   <!-- Bootstrap -->\r\n");
      out.write("   <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("   <!-- Waypoints -->\r\n");
      out.write("   <script src=\"js/jquery.waypoints.min.js\"></script>\r\n");
      out.write("   <!-- Carousel -->\r\n");
      out.write("   <script src=\"js/owl.carousel.min.js\"></script>\r\n");
      out.write("   <!-- countTo -->\r\n");
      out.write("   <script src=\"js/jquery.countTo.js\"></script>\r\n");
      out.write("\r\n");
      out.write("   <!-- Stellar Parallax -->\r\n");
      out.write("   <script src=\"js/jquery.stellar.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("   <!-- Magnific Popup -->\r\n");
      out.write("   <script src=\"js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("   <script src=\"js/magnific-popup-options.js\"></script>\r\n");
      out.write("\r\n");
      out.write("   <!-- Datepicker -->\r\n");
      out.write("   <script src=\"js/bootstrap-datepicker.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   <!-- Main -->\r\n");
      out.write("   <script src=\"js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
